### ISSUE TITLE
add a way to enlarge font with key combination

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#10]
Currently Termonad doesn't have any way to enlarge the font with a key combination.  You have to edit the `~/.config/termonad/termonad.hs` file and restart Termonad.  This is pretty annoying and should be fixed.

I used to use the terminal emulator Roxterm.  Roxterm has font resizing options like the following ("Zoom In", "Zoom Out", "Normal Size"):

![file2](https://user-images.githubusercontent.com/64804/44628791-2bc56700-a982-11e8-9cd9-23029193313f.png)

It would be great to have similar options for Termonad.  Adding this would require the following steps:

1.  Add a new menu entry for enlarging and shrinking [here](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/src/Termonad/XML.hs#L45-L91).

1.  Setup the callbacks for the options in the second half of [this function](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/src/Termonad/App.hs#L230).

1.  Within the callbacks, create a new [FontDescription](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/src/Termonad/Types.hs#L112), and then loop through the [existing terminals](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/src/Termonad/Types.hs#L84) and update their FontDescription.

1.  Bonus points if you change it so that a FontDescription is actually associated with a single terminal instead of the entire application.  That way the font size for a single terminal would be able to be increased instead of increasing the font sizes for all terminals.

1.  Extra bonus points if you add a configuration option that the user can set that says whether they want the Increase Font Size / Decrease Font Size buttons to change the font size of ALL terminals, or just the focused on.  Or, maybe add an extra button that increases the fontsize for all terminals??

**Comment by emmanueldenloye** [comment]
I just took a look at your code. Are you familiar with lenses? I think they could make changing the fonts in the terminal a much easier affair.

**Comment by cdepillabout** [comment]
Thanks for taking a look at this @emmanueldenloye!

Yeah, there should be lenses available in the [Termonad.Lenses](http://hackage.haskell.org/package/termonad-1.0.0.0/docs/Termonad-Lenses.html) module.  If you notice any record fields that don't have lenses, this would be considered a bug!

**Comment by emmanueldenloye** [comment]
I didn't realize you could make lenses in that way. That is rather convienent.

To make the font changes I was considering using a config hook. I could use a hook similar to:

`createTermHook :: TMState -> Terminal -> IO ()`

or even that one. I'll cook up something and see what shakes out.

**Comment by cdepillabout** [comment]
> To make the font changes I was considering using a config hook.

I don't think this would necessarily require using the config hook.

I think basically you just need to add a new menu entry for shrinking and enlarging the current font size.  A new menu entry should be added [here](https://github.com/cdepillabout/termonad/blob/cff560a43cca7ad210060da01d2de7653facd352/src/Termonad/App.hs#L314) and [here](https://github.com/cdepillabout/termonad/blob/cff560a43cca7ad210060da01d2de7653facd352/src/Termonad/XML.hs#L45).

In the callback for when you click on the menu entry, you basically need to take the current list of terminals, and loop over them setting the new font size.

An example of looping over existing terminals can be found [here](https://github.com/cdepillabout/termonad/blob/cff560a43cca7ad210060da01d2de7653facd352/src/Termonad/Term.hs#L197).

Here's the code that initially sets the font size:

https://github.com/cdepillabout/termonad/blob/cff560a43cca7ad210060da01d2de7653facd352/src/Termonad/Term.hs#L303

Creating the original font description can be found here:

https://github.com/cdepillabout/termonad/blob/cff560a43cca7ad210060da01d2de7653facd352/src/Termonad/App.hs#L152

You may have to refactor the code a little to make re-creating the font description easy?
