### ISSUE TITLE
Remove the single pixel white border around terminal

### ISSUE THREAD

**Issue by ssbothwell** [cdepillabout/termonad#129]
Termonad frames have a single pixel white border. I don't see anything in the configuration examples to remove this. Is it possible?

**Comment by cdepillabout** [comment]
@ssbothwell Thanks for bringing this up.

I never noticed the single pixel white border, but now that you've pointed it out, I can't _unsee_ it.

This was not intended.  If you (or anyone else) want to send a PR removing this single pixel boarder, I'd be happy to merge it.

**Comment by ssbothwell** [comment]
I haven't yet taken a look at the code base, but I would be interested in trying to fix this. Can you give me some suggestions about where to start looking to try to diagnose this?

**Comment by cdepillabout** [comment]
@ssbothwell Thanks!

> Can you give me some suggestions about where to start looking to try to diagnose this?

I'm not sure exactly where this could be coming from, but I have a few ideas.

Termonad is a really simple GTK app.  It has an outer [`GtkApplicationWindow`](http://hackage.haskell.org/package/gi-gtk-4.0.1/docs/GI-Gtk-Objects-ApplicationWindow.html), with a [`GtkBox`](http://hackage.haskell.org/package/gi-gtk-4.0.1/docs/GI-Gtk-Objects-Box.html) and [`GtkStack`](http://hackage.haskell.org/package/gi-gtk-4.0.1/docs/GI-Gtk-Objects-Stack.html) inside of it.  They are defined here:

https://github.com/cdepillabout/termonad/blob/45431404f6560cd45f2188bb29f46ba88af1665a/src/Termonad/XML.hs#L17-L40

Then, inside the `Stack` (or maybe it is the `Box`), there is a `Notebook` (which is the thing that holds the tabs):

https://github.com/cdepillabout/termonad/blob/45431404f6560cd45f2188bb29f46ba88af1665a/src/Termonad/App.hs#L313

When a new tab is created, the actual terminal is added to it:

https://github.com/cdepillabout/termonad/blob/45431404f6560cd45f2188bb29f46ba88af1665a/src/Termonad/App.hs#L363

https://github.com/cdepillabout/termonad/blob/45431404f6560cd45f2188bb29f46ba88af1665a/src/Termonad/Term.hs#L403-L408

Actually, the terminal widget is not added directly to the tab, but to the a [scrolled window](http://hackage.haskell.org/package/gi-gtk-4.0.1/docs/GI-Gtk-Objects-ScrolledWindow.html), which is added to the tab:

https://github.com/cdepillabout/termonad/blob/45431404f6560cd45f2188bb29f46ba88af1665a/src/Termonad/Term.hs#L423-L425

----------------------------------------------------------------------------------------------

My guess is that one of these things (whether it is the `ApplicationWindow`, the `Box`, the `Notebook`, the `ScrolledWindow`, or the actual [vte terminal](http://hackage.haskell.org/package/gi-vte-2.91.25/docs/GI-Vte-Objects-Terminal.html)) has a one pixel border (or margin or something) defined somewhere.

I'm not sure which is the most likely, or how to go about debugging where it occurs.

**Comment by ssbothwell** [comment]
Thanks! I'll see what I can do.

**Comment by Reasonable-Solutions** [comment]
to debug stuff like this, you set GTK_DEBUG=interactive and then you click around a bit.
In this case the relevant css is `notebook { border: none; }`

**Comment by cdepillabout** [comment]
Closed in #138.

@ssbothwell Thanks for bringing this up.

@Reasonable-Solutions Thanks for the tip about `GTK_DEBUG=interactive`.  I never knew about this!
