### ISSUE TITLE
load and save preferences from preferences dialog to file

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#133]
PR #130 (for issue #82) implemented a preferences dialog that allows the user to modify Termonad settings at runtime.

Here's what the preferences dialog currently looks like:

![image](https://user-images.githubusercontent.com/64804/67140838-90015500-f22c-11e9-8112-f90839e93bba.png)

However, as you can see from the warning, these settings are lost when you exit out of Termonad.

It would be nice if these settings could be serialized to a file, and loaded when Termonad starts.

There are a couple tricky parts about implementing something like this:

- In the preferences dialog, should there be two buttons, one for setting the preferences temporarily, and one for actually saving the preferences to a file (so the preferences will be loaded next time you start Termonad).  Would this be confusing for any users?
- What sort of file format should you serialize preferences to?  It would be nice to have something the user could edit with a text editor (like vim or emacs), but if you allowed this, then things like comments could potentially get overwritten the next time you serialized (saved) their preferences from Termonad.  Some sort of binary format that discourages hand-editing might be the best bet.
- The preferences serialization format should probably be versioned, so old preferences files could be read by newer versions of Termonad.
- If the user sets the same setting in both the preferences serialization file and their `~/.config/termonad/termonad.hs` file, which setting should be used?
- If the user modifies a setting in the preferences serialization file, maybe it could overwrite the value of the setting in the `~/.config/termonad/termonad.hs`.  However, what if the user decides that they don't want to use the setting from the preferences serialization file anymore, but instead to use the value of the setting from `~/.config/termonad/termonad.hs`.  There should be a way to only set _some_ settings in the preferences serialization file, without having to set _all_ settings in the preferences serialization file.  For instance, maybe you want the "Scrollback Length" setting to be managed in the preferences serialization file, but you want to set the "Cursor Blink Mode" in `~/.config/termonad/termonad.hs`.  Termonad should be flexible enough to handle this.

Although note that all of these problems don't necessarily have to be solved in the first PR implementing this.

------------------------------------------------------------------------------------------------

If you're interested in implementing this, here's the places in the code you'd need to look at:

-  The `defaultMain` function is the one that interacts with `dyre` to dynamically reload the `~/.config/termonad/termonad.hs` file:

    https://github.com/cdepillabout/termonad/blob/10f30d2e2ae5956e6eb3fb7df61b417d82283aa0/src/Termonad/App.hs#L889-L909

    This function might have to be modified to try to load settings from the serialized preferences file.  Or maybe the `start` function would be a better candidate.

    https://github.com/cdepillabout/termonad/blob/10f30d2e2ae5956e6eb3fb7df61b417d82283aa0/src/Termonad/App.hs#L824-L831

- This is the function that shows the preferences dialog and actually sets the preferences:

    https://github.com/cdepillabout/termonad/blob/10f30d2e2ae5956e6eb3fb7df61b417d82283aa0/src/Termonad/App.hs#L710

    This function will have to be modified to possibly serialize the preferences to a file.

    You might want to create a separate datatype to represent the preferences we are serializing.

- The layout of the actual preferences dialog is in `glade/preferences.glade`.  You probably want to use [Glade](https://glade.gnome.org/) to add new buttons to this dialog.

**Comment by jecaro** [comment]
I think a simple mechanism which covers most use cases would be:

1. If there is no config file, Termonad writes it with the default settings. Then, when the user validates the preferences dialog, it applies the settings and overrides the config file as well. The warning label is not shown in this case. This is the way most software handle this, so it is the expected behavior. It will be nice for new comer to Termonad and "basic users".

2. And for "power users", who have a `termonad.hs`. We can make their `termonad.hs` file take precedence over the config file. The behavior stays the same but the warning label is shown.

What do you think ?

**Comment by cdepillabout** [comment]
@jecaro Sorry for taking a while to get back to you about this!

I think the strategy you have proposed is a good solution.  If you want to send a PR implementing this, I would accept it!

**Comment by jecaro** [comment]
Great, I'll start working on this very soon.

**Comment by cdepillabout** [comment]
This has mostly been implemented in #140.

This is implemented as described in https://github.com/cdepillabout/termonad/issues/133#issuecomment-548697841.

At some point, it might be nice to figure out a way to an end-user to use both preferences from the preferences file in `~/.config/termonad/termonad.yaml`, and the Haskell settings in `~/.config/termonad/termonad.hs`.

But for now, I think forcing the user to use one or the other should be fine.
