### ISSUE TITLE
Typing feels sluggish, can this be quantified?

### ISSUE THREAD

**Issue by NorfairKing** [cdepillabout/termonad#135]
I'm considering using termonad instead of urxvt, but something doesn't feel right. Is there a delay in how fast a character appears after you type it? Can this be quantified somehow?

**Comment by cdepillabout** [comment]
Hi @NorfairKing.

As far as the Termonad code base is concerned, there isn't a delay programmed anywhere for how fast a character appears.

I do most of my development on a fast computer, so I haven't noticed any sort of delay.  I just tried opening up `xterm` and comparing it to typing in Termonad, and I couldn't really tell a difference.

I did have two thoughts about this though.

1. The keyboard handling in Termonad isn't _super_ well thought-out.  

    Handling keys like `Shift-Ctrl-t` (for opening a new tab) is done with menu accelerators in GTK.  So in the `File` menu, there is a menu option for `New Tab`, and it has an accelerator of `Shift-Ctrl-t`.  It is set here:

    https://github.com/cdepillabout/termonad/blob/538b93e58a5b4ca633694fa8de6e58357bf9bd65/src/Termonad/App.hs#L415-L418

    My guess is that this is probably not going to cause the problems you're seeing, since it is mostly handled directly by GTK.  I imagine GTK has been at least somewhat optimized for efficiency here.

2. There is another way Termonad handles keyboard input.

    In order to handle switching between multiple open tabs, I directly read all the characters typed into a terminal and do something special when the user types `Alt-1`, `Alt-2`, etc.

    That happens here:

    https://github.com/cdepillabout/termonad/blob/538b93e58a5b4ca633694fa8de6e58357bf9bd65/src/Termonad/Keys.hs#L110-L120

    Since this happens on every key press, it is possible this is causing slowness for you.

    Would you be able to comment out these two lines of code (where `handleKeyPress` gets set up as a callback), and see if this improves the sluggishness for you?

    https://github.com/cdepillabout/termonad/blob/538b93e58a5b4ca633694fa8de6e58357bf9bd65/src/Termonad/Term.hs#L447-L448

    (If you're using a `~/.config/termonad/termonad.hs` file, be sure to remove the cached Termonad binary at `~/.cache/termonad` so that you don't accidentally get an old version of Termonad.  If you can use `Atl-1` or `Alt-2` to switch between tabs, you will know that you haven't correctly commented out the two lines of code.)

If you're able to fix the sluggishness by commenting out the `handleKeyPress` callback, then I will refactor the tab switching code to use accelerators, which will hopefully get rid of this problem for you.

If you're _not_ able to fix the sluggishness by commenting out the `handleKeyPress` callback, then my guess is that this is actually a [VTE](https://wiki.gnome.org/Apps/Terminal/VTE) problem.  My suggestion would be to try a few other terminal emulators that use the VTE library (like `roxterm` or `gnome-terminal`) and see if you experience the sluggishness there as well.

**Comment by NorfairKing** [comment]
@cdepillabout Thank you for the very detailed comment.
I just tried out `roxterm` and it has the same feeling.
I don't want to waste any more of your time, especially because this issue is about my "feeling', so it would be nice if there was a way to check how long it took to render a character (and then do the same in `urxvt`).

**Comment by cdepillabout** [comment]
> it would be nice if there was a way to check how long it took to render a character (and then do the same in urxvt).

I agree that this would be nice.

Unfortunately, this needs to be almost entirely handled by VTE.  You'd have to instrument the VTE code base with some sort of timing/profiling type functions.  Then you'd need to add a way to turn them on from the Termonad (or Roxterm) code base.

If you're interested in this, I'd recommend opening an issue about it on [VTE repo](https://gitlab.gnome.org/GNOME/vte).  I'm sure they would be interested in improving performance in their code base, but an extensive profiling functionality could be a very intrusive change.  I'm not sure what their reaction would be.

**Comment by cdepillabout** [comment]
I'm going to close this since we haven't done anything about this in the past year, and I think this should mostly be a problem in the VTE codebase.

However if someone else is experiencing this, or it could be shown to be a problem in Termonad, please feel free to reopen.
