### ISSUE TITLE
Make sure that the example .config/termonad/termonad.hs file in the README actually compiles

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#14]
In the [README.md](https://github.com/cdepillabout/termonad/blob/master/README.md) there is an example configuration file for Termonad, `.config/termonad/termonad.hs`.  It would be great to check that this actually compiles.

There is a library that will do this called `markdown-unlit`.  I have an example of using it [here](https://github.com/arow-oss/tonatona/pull/31/files).  This should be used to check that the example Termonad's README compiles.

**Comment by Grendel-Grendel-Grendel** [comment]
Hey, I think I've solved this issue. Made a test suite for the readme, used the markdown-unlit. The stack test found no errors

New to actually contributing on github so I'm not sure how to share this. I attempted making a branch 
and pushing the edited termonad.cabal file with the test suite but I don't think I have permissions.

Here is the test suite I added to the termonad.cabal file. Apologies for no code tags but it seemed to be messing up indentation which I figured would be more annoying.

test-suite readme
  type:           exitcode-stdio-1.0
  main-is:        README.lhs
  hs-source-dirs: test
  build-depends:  base
                  , markdown-unlit
                  , termonad
                  , colour
  ghc-options: -pgmL markdown-unlit
