### ISSUE TITLE
apt installed version doesn't boot

### ISSUE THREAD

**Issue by tom-audm** [cdepillabout/termonad#146]
```
$ cat /etc/debian_version 
10.3
$ sudo apt install termonad
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  termonad
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 4,983 kB of archives.
After this operation, 47.6 MB of additional disk space will be used.
[...]
Preparing to unpack .../termonad_0.2.1.0-2_amd64.deb ...
Unpacking termonad (0.2.1.0-2) ...
Setting up termonad (0.2.1.0-2) ...

$ termonad
termonad: Failed to open file “/usr/share/termonad/img/termonad-lambda.png”: No such file or directory (4)
```

**Comment by cdepillabout** [comment]
@tom-audm Sorry you're having trouble with Termonad.

However, the version of Termonad you're using is quite old, and I don't have any control over how Termonad is packaged in other distros.

I'd suggest trying to install from source with a tool like `stack`.

-----------------------------

As for your specific problem:

> termonad: Failed to open file “/usr/share/termonad/img/termonad-lambda.png”: No such file or directory (4)

I believe Termonad uses the above image as an icon.  The file `/usr/share/termonad/img/termonad-lambda.png` should have been installed by the `termonad` package on your system.  If it is not, I'd recommend filing a bug against the Debian Termonad package.

As a quick workaround, you can download https://github.com/cdepillabout/termonad/blob/master/img/termonad-lambda.png and move it to `/usr/share/termonad/img/termonad-lambda.png`.  Maybe Termonad will start working then?
