### ISSUE TITLE
doctests hang when compiling with nix

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#15]
The doctests for termonad appear to hang when compiling with `nix-build`.  Because of this I have disabled them in the [`termonad.nix`](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/.nix-helpers/termonad.nix#L17) file.

Here is what it looks like when running `nix-build`:

```sh
$ cd termonad/
$ nix-build
...
Running 2 test suites...
Test suite termonad-test: RUNNING...
Test suite termonad-test: PASS
Test suite logged to: dist/test/termonad-0.2.1.0-termonad-test.log
Test suite doctests: RUNNING...
```

It just hangs here.  `doctest` appears to fork multiple threads and use 100% of the CPU, but nothing seems to happen.

The doctests work when run with `stack`, even on NixOS.

**Comment by cdepillabout** [comment]
I wonder if this is related to https://github.com/sol/doctest/issues/219.

**Comment by cdepillabout** [comment]
I've figured out that this seems to be caused the by the configure options declared in the generic Haskell builder:

https://github.com/NixOS/nixpkgs/blob/d73f16d6767e99675682f822dac3017bf9af1e83/pkgs/development/haskell-modules/generic-builder.nix#L151-L166

Commenting out all those options appears to make the doctests succeed in just a minute or two.  I'm currently trying to figure out which option is to blame.

**Comment by cdepillabout** [comment]
I figured this out and posted sent a PR about it upstream:

https://github.com/NixOS/nixpkgs/pull/58743

**Comment by cdepillabout** [comment]
This appears to be the corresponding GHC issue:

https://gitlab.haskell.org/ghc/ghc/issues/15524#note_193060

**Comment by cdepillabout** [comment]
I finally fixed this in #113.

**Comment by n4074** [comment]
I'm encountering this issue while trying to build the latest version of Termonad on Nixos 19.03, with the following Nixos configuration:

```nix
{ config, pkgs, ... }:
let
  termonad = builtins.fetchGit {
    url = "https://github.com/cdepillabout/termonad";
    ref = "master";
  };
in
{
  environment.systemPackages = with pkgs; [
    (import "${termonad}/.nix-helpers/termonad-with-packages.nix" { })
  ];
}
```

As described, the doctest run takes 100% and eventually gets OOM-killed. For now I'm bypassing the issue by disabling tests:

```nix
{ config, pkgs, ... }:
let
  termonad = builtins.fetchGit {
    url = "https://github.com/cdepillabout/termonad";
    ref = "master";
  };

  additionalOverlays = [
    (self: super: {
      haskell = super.haskell // {
        packageOverrides = hself: hsuper:
          super.haskell.packageOverrides hself hsuper // {
            termonad = self.haskell.lib.dontCheck hsuper.termonad;
          };
      };
    })
  ];
in
{
  environment.systemPackages = with pkgs; [
    (import "${termonad}/.nix-helpers/termonad-with-packages.nix" { inherit additionalOverlays; })
  ];
}
```

Is this expected? Is the fix you referenced only applicable for 19.09? Thanks.

**Comment by cdepillabout** [comment]
@n4074 Thanks for this report.  

However, I just tried compiling this and running the doctests at the current HEAD of `master`, and it appears that the doctests finish within a minute or so.


> ```nix
> { config, pkgs, ... }:
> let termonad = builtins.fetchGit { url = "https://github.com/cdepillabout/termonad"; ref = "master"; }; in {
>   environment.systemPackages = with pkgs; [ (import "${termonad}/.nix-helpers/termonad-with-packages.nix" { }) ];
> }
```

In this setup, you are basically pulling the `termonad` executable from how it is defined in this repo.  So since the doctests run fast on my machine, I am very fast that they take a long time on your machine, since all the inputs to the termonad derivation should be the same.

I'm not sure what could be causing any difference here.

However, if you can't figure out what could be going on, maybe you'd like to send a PR adding a top-level option to `default.nix` (and `.nix-helpers/termonad-with-packages.nix`) to disable running tests?  That should at least let you work around the problem a little easier.

**Comment by cdepillabout** [comment]
Another thing you could try doing is just getting termonad from a recent release of nixpkgs.

Here is nixpkgs-unstable as of today:

```console
$ cd /some/path/to/nixpkgs
$ git checkout master
$ git pull
$ nix repl ./.
> termonad-with-packages   
«derivation /nix/store/gnil59dy229r729g6x8izzl9hsa4pml0-termonad-with-packages-8.6.5.drv»
> haskellPackages.termonad
«derivation /nix/store/99py0xvjjpgdcgj03ks160kyfd7mp266-termonad-2.0.0.0.drv»
```

The top-level `termonad-with-packages` is already using `termonad-2.0.0.0`, which is the latest release.

**Comment by n4074** [comment]
Thanks for your response @cdepillabout . When I upped the RAM on the VM from 4GB to 8GB the doctests started finishing reasonably quickly. I guess it just uses a lot more memory than expected.
