### ISSUE TITLE
Error on WSL and Windows.

### ISSUE THREAD

**Issue by Unrooted** [cdepillabout/termonad#152]
I was just thinking and trying if there's a way to do that on both of them. I'm not really into Haskell that much, but those are the errors I got: 
![image](https://user-images.githubusercontent.com/30440603/82935029-bc343f80-9f8c-11ea-8ebc-b1000241517f.png)
![image](https://user-images.githubusercontent.com/30440603/82935041-be969980-9f8c-11ea-8100-0ed120e1de50.png)
Maybe they'll tell you something more than they're saying to me. I hope that this helps you at least in 'some' way, maybe in the further development of this. I tried it on my ArcoLinux VM and it seems pretty cool.
I was just thinking about it since Microsoft is bringing GUI app support and GPU hardware acceleration to the WSL soon, so it would be pretty great to have Termonad running on Windows via WSL with the X server.

**Comment by cdepillabout** [comment]
@Unrooted Thanks for submitting this bug.

I've never tried building Termonad on Windows (or WSL), so I'm not sure if it will work.

As for the error you're seeing, my guess is that the version of the `stack` build tool you're using is too old.

Here's the version I'm using locally:

```console
$ stack --version
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0
```

My guess is that if you upgrade `stack`, you will get further in the build process (although I don't know how far...)

**Comment by Unrooted** [comment]
Here's what I've got trying both `stack upgrade` and `stack --version`: 
![image](https://user-images.githubusercontent.com/30440603/82985174-d9502900-9ff3-11ea-889f-bae3e7b62fc1.png)
It was added to the PATH. 
Since WSL does have full Linux kernel, I thought about building it. Also, `stack` works well on Windows, that's what it always did. Build process should work fine as it is with other Haskell stuff on both Windows and WSL. I don't know what to do.

**Comment by cdepillabout** [comment]
Hmm, I don't know why you could be having this problem.

The other thought I had is that maybe a problem could be caused because the `stack.yaml` file is a symlink?

```console
$ ls -lah stack.yaml
lrwxrwxrwx 1 illabout illabout 17 Mar  2 19:54 stack.yaml -> stack-lts-15.yaml
```

If you did something like `mv stack-lts-15.yaml stack.yaml` and then `stack build`, does that work?

**Comment by Unrooted** [comment]
Okay, I've tried what you said and after this it builds:
![image](https://user-images.githubusercontent.com/30440603/83053257-c15ac280-a050-11ea-80d3-832bd6d15f77.png)
After trying `stack run` I've got a problem, like this: 
![image](https://user-images.githubusercontent.com/30440603/83050820-64114200-a04d-11ea-9329-e13fdbac3dfb.png)
But then, I've installed Vcxsrv, configured it, done config on the Ubuntu side, then I tried `stack run` again and it works perfectly fine using an X server.
![image](https://user-images.githubusercontent.com/30440603/83053272-c61f7680-a050-11ea-8076-99fde8cd5a7f.png)
Do you mind if I make a PR and add info about installing and using Termonad on a Windows machine?

**Comment by cdepillabout** [comment]
>  Do you mind if I make a PR and add info about installing and using Termonad on a Windows machine?

Yes, please do!  That would be great.

I'm glad you got this working.
