### ISSUE TITLE
missing termonad module

### ISSUE THREAD

**Issue by formula-spectre** [cdepillabout/termonad#153]
os: manjaro, installed via stack. config: the solarized example one. when executing termonad similar error are given:  
/tmp/cabal-install.-2163/dist-newstyle/tmp/src-2164/ghc-paths-0.1.0.12/dist/setup/setup.hs:10:1:
error:
Could not find module ‘Termonad.Config.Vec’
There are files missing in the ‘Cabal-3.2.0.0’ package,
try running 'ghc-pkg check'.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
example above.

**Comment by cdepillabout** [comment]
Hmm, so this seems somewhat strange.

You've said you installed with `stack`, but the error you've given has a path with `cabal-install` and `dist-newstyle` in the name, which makes me think you're trying to do something strange.

I'm not sure exactly what is going on, but my guess is that you've installed Termonad with `stack`, but you're trying to run `termonad` with `cabal`?

If you wanted to try to debug this, could you list all the commands you've used to both install Termonad, and then run it?  (Including things like whether or not the Termonad window opens, etc)

**Comment by formula-spectre** [comment]
that was an example when trying to install something with cabal.

**Comment by cdepillabout** [comment]
@formula-spectre If you want me to try to help debug this, could you list all the commands you've used to both install Termonad, and then run it? (Including things like whether or not the Termonad window opens, whether you are using cabal or stack, etc)

**Comment by cdepillabout** [comment]
I'm going to go ahead and close this since there hasn't been any activity recently.  Please feel free to respond or reopen if you're still running into this.
