### ISSUE TITLE
Stack Build fails because of ambiguous occurences

### ISSUE THREAD

**Issue by Lockne** [cdepillabout/termonad#162]
Hello! 
Beginner Haskell user here.

When building Termonad with Stack, I get the following error when compiling `src/Termonad/App.hs:`

` Ambiguous occurrence ‘fail’
    It could refer to either ‘Termonad.Prelude.fail’,
                             imported from ‘Termonad.Prelude’ at src/Termonad/App.hs:5:1-23
                             (and originally defined in ‘GHC.Base’)
                          or ‘Control.Monad.Fail.fail’,
                             imported from ‘Control.Monad.Fail’ at src/Termonad/App.hs:9:28-31
    |
417 |             fail $
`

I got similar errors when compiling the `Types.hs` and  `Gtk.hs` files. As a workaround, I went into those individual files and set `import Termonad.Prelude` to `import Termonad.Prelude hiding (fail)`. All the files compiled successfully after! 

Not sure if this is a valid issue, but I just wanted to bring it to notice!

**Comment by cdepillabout** [comment]
@Lockne Thanks for posting this issue!

My guess as to what is happening is that you're trying to build an older version of Termonad with a newer Stackage LTS (newer GHC), and this error is occurring.

Would you be able to try to rebuild with the latest release of Termonad (or just use the current `master` branch, which is at commit 95eb538b as of this writing)?

That should hopefully work for you.  I also have a CI build running for this, so I'm pretty-hopeful it will work: https://github.com/cdepillabout/termonad/runs/869535748

If this doesn't work, please let me know all the commands you're using to build Termonad, and the versions of all tools involved (mainly `stack`).

**Comment by Lockne** [comment]
@cdepillabout Thanks for the reply. It was very helpful!

I had indeed cloned the latest release of Termonad yesterday.

Initially I built  Termonad with the command `stack build --resolver lts-14.25` using `GHC 8.6`. That's when I got the errors. But today, following your suggestion, I rebuilt Termonad after upgrading to `GHC 8.8` - which was not installed on my laptop when I was building it the first time. I had failed to read the comment in the cabal file that said Termonad supports only `GHC 8.8`. 

After upgrading to GHC 8.8, Termonad compiled without a hitch!

**Comment by cdepillabout** [comment]
Ah, sorry, I had thought that this line would stop you from being able to use GHC-8.6:

https://github.com/cdepillabout/termonad/blob/95eb538bcfbeba1a7291b5abfaa4053b66db0587/termonad.cabal#L57

I thought this would force you to use GHC-8.8 (since the `base` package is tied to a specific version of GHC).  However, I guess this didn't work.

Oh well, at least you got it working!  Thanks for updating this.  I'll go ahead and close this issue, but if you have any other troubles, feel free to open an new issue.
