### ISSUE TITLE
Documentation missing from hackage for 0.4.0.0

### ISSUE THREAD

**Issue by ShrykeWindgrace** [cdepillabout/termonad#163]
Hi!

It seems that the haddock documentation is missing from hackage for the latest `termonad` (https://hackage.haskell.org/package/termonad).

The previous version is ok (https://hackage.haskell.org/package/termonad-3.1.0.1).

**Comment by cdepillabout** [comment]
Thanks for letting me know.  I just uploaded the docs for 4.0.0.0.
