### ISSUE TITLE
Add `show menu` menu option to context menu

### ISSUE THREAD

**Issue by maridonkers** [cdepillabout/termonad#170]
(So that a disabled menu can again be enabled without having to manually edit the settings file.)

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.67, NixOS, 20.03.3077.ad246fb8745 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3077.ad246fb8745"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cdepillabout** [comment]
This is a good suggestion, thanks!

For anyone interested in implementing this, you can edit the menu in this block of code:

https://github.com/cdepillabout/termonad/blob/8f39a234795080b5e82a464fe1224f6b3f5a592c/src/Termonad/Term.hs#L473-L485

I'm not sure the best way to define an action (like the `app.copy` and `app.paste` in the above code), but `app.copy` and `app.paste` are also used here:

https://github.com/cdepillabout/termonad/blob/8f39a234795080b5e82a464fe1224f6b3f5a592c/src/Termonad/App.hs#L443-L448

https://github.com/cdepillabout/termonad/blob/8f39a234795080b5e82a464fe1224f6b3f5a592c/src/Termonad/XML.hs#L73-L78

**Comment by maridonkers** [comment]
Adding the existing preferences dialog to the context menu is the easier way --a single line of code-- and also makes the Show menu option and more available.

``` haskell
-- | Popup the context menu on right click
handleMousePress :: Terminal -> EventButton -> IO Bool
handleMousePress vteTerm event = do
  button <- getEventButtonButton event
  let rightClick = button == fromIntegral BUTTON_SECONDARY
  when rightClick $ do
    menuModel <- menuNew
    menuAppend menuModel (Just "Copy") (Just "app.copy")
    menuAppend menuModel (Just "Paste") (Just "app.paste")
    menuAppend menuModel (Just "Preferences") (Just "app.preferences") --added line
```
Have changed, built and tried it on NixOS (via nix-build) and it works fine. This looks like a great opportunity to create my first pull request. Let me read up on that.

**Comment by cdepillabout** [comment]
@maridonkers Sounds like a good idea, please do!
