### ISSUE TITLE
doctests segfault when run with ghc-8.10.3

### ISSUE THREAD

**Issue by peti** [cdepillabout/termonad#174]
Citing from https://hydra.nixos.org/build/133745495:

~~~
Running 2 test suites...
Test suite doctests: RUNNING...
Test suite doctests: FAIL
Test suite logged to: dist/test/termonad-4.0.1.1-doctests.log
~~~

The output is not particularly helpful, I'm afraid.

**Comment by sternenseemann** [comment]
Log from building manually:

```
running tests
Running 2 test suites...
Test suite doctests: RUNNING...

/build/termonad-4.0.1.1/src/Termonad/Term.hs:368:5: warning: [-Wdeprecations]
    In the use of ‘terminalSpawnSync’
    (imported from GI.Vte, but defined in GI.Vte.Objects.Terminal):
    Deprecated: "(Since version 0.48)
                 Use 'GI.Vte.Objects.Terminal.terminalSpawnAsync' instead."
    |
368 |     terminalSpawnSync
    |     ^^^^^^^^^^^^^^^^^

/build/termonad-4.0.1.1/src/Termonad/App.hs:446:21: warning: [-Wdeprecations]
    In the use of ‘terminalCopyClipboard’
    (imported from GI.Vte, but defined in GI.Vte.Objects.Terminal):
    Deprecated: "(Since version 0.50)
                 Use 'GI.Vte.Objects.Terminal.terminalCopyClipboardFormat' with 'GI.Vte.Enums.FormatText'
                   instead."
    |
446 |     maybe (pure ()) terminalCopyClipboard maybeTerm
    |                     ^^^^^^^^^^^^^^^^^^^^^
free(): double free detected in tcache 2

/build/termonad-4.0.1.1/src/Termonad/Term.hs:368:5: warning: [-Wdeprecations]
    In the use of ‘terminalSpawnSync’
    (imported from GI.Vte, but defined in GI.Vte.Objects.Terminal):
    Deprecated: "(Since version 0.48)
                 Use 'GI.Vte.Objects.Terminal.terminalSpawnAsync' instead."

/build/termonad-4.0.1.1/src/Termonad/App.hs:446:21: warning: [-Wdeprecations]
    In the use of ‘terminalCopyClipboard’
    (imported from GI.Vte, but defined in GI.Vte.Objects.Terminal):
    Deprecated: "(Since version 0.50)
                 Use 'GI.Vte.Objects.Terminal.terminalCopyClipboardFormat' with 'GI.Vte.Enums.FormatText'
                   instead."
*** Exception: <stdout>: hPutChar: resource vanished (Broken pipe)
Test suite doctests: FAIL
Test suite logged to: dist/test/termonad-4.0.1.1-doctests.log
Test suite termonad-test: RUNNING...
Test suite termonad-test: PASS
Test suite logged to: dist/test/termonad-4.0.1.1-termonad-test.log
1 of 2 test suites (1 of 2 test cases) passed.
```

Seems like an I/O issue rather than a genuine test failure.

**Comment by cdepillabout** [comment]
Running the doctests directly appears to give an segfault.

```
$ git clone git@github.com:cdepillabout/termonad.git
$ cd termonad/
$ git checkout e4fd607c7e0bc7 # this is a commit that I know to be frequently failing
$ nix-build # this should probably fail because of the doctests test
...
... failed to build 
$ nix-shell # the following commands are run in a nix-shell
$ cabal test termonad:doctests
...
/home/illabout/git/termonad/src/Termonad/App.hs:445:21: warning: [-Wdeprecations]
    In the use of ‘terminalCopyClipboard’
    (imported from GI.Vte, but defined in GI.Vte.Objects.Terminal):
    Deprecated: "(Since version 0.50)
                 Use 'GI.Vte.Objects.Terminal.terminalCopyClipboardFormat' with 'GI.Vte.Enums.FormatText'
                   instead."
Examples: 44  Tried: 44  Errors: 0  Failures: 0
Test suite doctests: FAIL
Test suite logged to:
/home/illabout/git/termonad/dist-newstyle/build/x86_64-linux/ghc-8.10.3/termonad-4.0.1.1/test/termonad-4.0.1.1-doctests.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal: Tests failed for termonad-4.0.1.1.
$ dist-newstyle/build/x86_64-linux/ghc-8.10.3/termonad-4.0.1.1/build/doctests/doctests
...
Segmentation fault
```

Sometimes running `cabal test` or the doctests directly doesn't segfault, but works correctly.  It appears to be randomly segfaulting.

I've only confirmed this after updating to ghc-8.10.3.  This doesn't appear to be happening with ghc-8.10.2.  The following diff can be used to test ghc-8.10.2:

```diff
diff --git a/.nix-helpers/nixpkgs.nix b/.nix-helpers/nixpkgs.nix
index 7e81589..e971269 100644
--- a/.nix-helpers/nixpkgs.nix
+++ b/.nix-helpers/nixpkgs.nix
@@ -32,7 +32,7 @@ let
         }
       else nixpkgs;
 
-  compilerVersion = if isNull compiler then "ghc8103" else compiler;
+  compilerVersion = if isNull compiler then "ghc8102" else compiler;
 
   # An overlay that adds termonad to all haskell package sets.
   haskellPackagesOverlay = self: super: {
```

Maybe there is some sort of bad interaction between GHC-8.10.3 and `doctest`?  Or possibly the problem is that I'm using `cabal-doctests`, and that sets up the environment incorrectly?  Or maybe there is some problem with using a Nix-compiled GHC?

**Comment by cdepillabout** [comment]
I've released a new version on Hackage that disables the doctests when building with ghc-8.10.3: https://hackage.haskell.org/package/termonad-4.0.1.2.

This should work-around the test failure and get Termonad building again in nixpkgs.

However, I haven't actually figured out the underlying problem.

**Comment by peti** [comment]
My impression is that running doctest as a Cabal test suite is way too fragile to be worthwhile. I've tried to do in some of my packages and I've had so much trouble that I ultimately ended up adopting the view that doctest is something you run in CI, but not at build time. I've been much happier since and I've also been able to convert those packages back to a `Simple` build type, which is pretty desirable IMHO.

**Comment by cdepillabout** [comment]
One of the big problems is that doctest requires one package-db/environment to be available when the cabal test suite is compiled, and a _different_ package-db/environment to be available when the test suite is actually run.  Cabal doesn't provide any way of describing this situation, because it doesn't have any support for describing "run-time" haskell dependencies.

Because of this, doctests end up getting run differently depending on whether they are being run with `stack`, `cabal` or our nix infrastructure.

`cabal-doctest` does a pretty good job of working around all these difficulties, but in this case, I have no idea where a segfault would be coming from.

**Comment by quasicomputational** [comment]
I'm just trying to reproduce this but failing at an early hurdle (getting some of the GTK bindings installed). Is this only happening on Nix, or is it happening with Stack and cabal-install as well?

I had a look at the doctest set up for termonad and it looks okay to me.

Can this be reproduced without doctest in the loop? doctest is, fundamentally, a wrapper around GHCi; if you can reproduce the segfault in GHCi, that means it's either a GHC bug (my guess is in the GHCi linker) or, if it's Nix-specific, some unfortunate interaction there.

**Comment by cdepillabout** [comment]
> I'm just trying to reproduce this but failing at an early hurdle (getting some of the GTK bindings installed).

Thanks a lot for taking a look at this!

The GTK dependencies are quite annoying to install if you're not using Nix.

> Is this only happening on Nix, or is it happening with Stack and cabal-install as well?

I just took a look at building Termonad on Debian with `stack` (without Nix involved at all).  I have been able to reproduce the segfaults, again with only GHC-8.10.2.

> Can this be reproduced without doctest in the loop?

This is a good idea, but unfortunately I don't know enough about `doctest` to be able to reproduce this.

If I had more time, I'd like to have a debug build of `doctest` where I do some `printf`-debugging to figure out exactly what line is failing.  If I could figure this out, then I'd hopefully also be able to reproduce it directly with GHCi.  It is entirely possible that this is just a GHC bug that I am incorrectly attributing to doctest.

**Comment by j6carey** [comment]
This is just speculation, but [GHC bug 19149](https://gitlab.haskell.org/ghc/ghc/-/issues/19149) might be relevant.

**Comment by cdepillabout** [comment]
@j6carey Great find, thanks for letting me know!

Although it seems strange that this bug would only be triggered when running under doctest, and not during normal use.

It looks like there will be a fix in GHC 8.10.4, so I'll be on that lookout for that.

**Comment by j6carey** [comment]
Well, it might be triggered under normal use too, and in any case I have no direct evidence.  It's mainly that it is: 1) a crash, and 2) specific to 8.10.3.  Those match this issue.

**Comment by cdepillabout** [comment]
I sent a PR where I try bumping to ghc-8.10.4, but the doctests still appear to randomly fail, similar to 8.10.3: https://github.com/cdepillabout/termonad/pull/182

**Comment by j6carey** [comment]
Ah, that's too bad.  I'd hoped it would help.

**Comment by j6carey** [comment]
Running doctest as a separate process seems to avoid the problem.

**Comment by cdepillabout** [comment]
@j6carey That's good to know.  I'll have to try that out.

Is the package you implemented this for open source?  Could you link to the source code?

**Comment by j6carey** [comment]
I'm afraid not, but it's really simple.  In the `Main.hs` for your doctest target, replace
```
import Test.DocTest (doctest)

arguments :: [String]
arguments = _

main :: IO ()
main = doctest arguments
```
with
```
import System.Process (proc, waitForProcess, withCreateProcess)

arguments :: [String]
arguments = _

main :: IO ()
main = withCreateProcess (proc "doctest" arguments) (\_ _ _ h -> waitForProcess h >>= exitWith)
```
(Assuming that I didn't make some typo.)

In the .cabal file, keep the `doctest` in the `build-depends` for the doctest target to ensure that `cabal2nix` picks up the dependency upon the `doctest` package and thus includes `doctest` in the path.  Of course, add `process` to the `build-depends`.

Hopefully that does the trick.

**Comment by cdepillabout** [comment]
@j6carey Thanks for the recommendation.

I sent a PR implementing this in https://github.com/cdepillabout/termonad/pull/183.  As far as I can tell, it no longer crashes!

There are still two things I wanted to check with this:

- [ ] check if using `forkOS` or `forkIO` and running the `doctest` function (instead of calling out to the `doctest` executable) crashes
- [ ] check if this also works when building in Nix

**Comment by cdepillabout** [comment]
I sent a commit 70748cc on #183 that attemps to use `forkIO`, `forkOS`, and `forkProcess` to run the `doctest` function (instead of calling out to the `doctest` executable), but none of these appear to work.

The only thing that appears to work is directly calling the `doctest` executable.

**Comment by cdepillabout** [comment]
@j6carey In cdab2d8 from #183 I was able to run doctests normally by just removing `-with-rtsopts=-N`.  I tried this because I noticed that the `doctest` binary doesn't have this set in the cabal file.

Maybe this is the simplest explanation.

**Comment by cdepillabout** [comment]
Here's another GHC segfault that only happens in 8.10.{3,4} that might be related: https://gitlab.haskell.org/ghc/ghc/-/issues/19417

**Comment by cdepillabout** [comment]
I've fixed this in https://github.com/cdepillabout/termonad/pull/188.
