### ISSUE TITLE
stack install failed: error while loading shared libraries: libHSsafe-exceptions

### ISSUE THREAD

**Issue by MarkuBu** [cdepillabout/termonad#192]
I tried to install termonad on Arch, but it failed with this error message

```
$ stack install
stack: error while loading shared libraries: libHSsafe-exceptions-0.1.7.1-2nQDIOXsnVo6dXNiCfbAXS-ghc8.10.4.so: cannot open shared object file: No such file or directory
```

I have a really basic installation (just base, xorg and xmonad). Maybe I miss some package you normally would have?

**Comment by cdepillabout** [comment]
`libHSsafe-exceptions-0.1.7.1-2nQDIOXsnVo6dXNiCfbAXS-ghc8.10.4.so` is the shared library for the [`safe-exceptions`](https://hackage.haskell.org/package/safe-exceptions) package (which I assume is a transitive dependency of Termonad).

This is a strange error, and not something I ever see before.  It is quite unusual for `stack` to not be able to load a shared library that it presumably has built.

My guess is that there is something strange in your `stack` setup.  I'd suggest deleting `~/.stack` (and `.stack-work/`?), and try rebuilding everything all again.

This doesn't seem like a problem with Termonad, so I'll go ahead and close it.  Although if it does end up being a problem with Termonad, I'm happy to re-open it.
