### ISSUE TITLE
Could not find module ‘Termonad.App’, ’Termonad.Config`, Termonad.Config.Colour

### ISSUE THREAD

**Issue by Minda1975** [cdepillabout/termonad#197]
Hello. Sorry for my bad English. I run Termonad, installed from Debian 11 repo (Termonad version 4.0.0.1-1). It runs fine. But when I try run it from another terminal, when i type `termonad`, it launches, but i see this errors:

```haskell
/home/azg256/.config/termonad/termonad.hs:5:1: error:
    Could not find module ‘Termonad.App’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import Termonad.App (defaultMain)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

/home/azg256/.config/termonad/termonad.hs:6:1: error:
    Could not find module ‘Termonad.Config’
    Perhaps you meant XMonad.Config (from xmonad-0.15)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import Termonad.Config
  | ^^^^^^^^^^^^^^^^^^^^^^...

/home/azg256/.config/termonad/termonad.hs:11:1: error:
    Could not find module ‘Termonad.Config.Colour’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
11 | import Termonad.Config.Colour

```

I did not create termonad.hs config file in `~/.config/termonad/` dir. My question would be how to solve this problem.

Thank you.

**Comment by cdepillabout** [comment]
The problem here is that when you run `termonad`, it tries to compile `~/.config/termonad/termonad.hs`.  It uses the `ghc` it finds on the `PATH` to do so.

If this GHC doesn't know about the `termonad` Haskell library, then it won't be able to find modules like `Termonad.App`.

I have a section in the README that talks about this.  Although it is somewhat confusing, so left me know if there is anything that doesn't make sense here: https://github.com/cdepillabout/termonad#compiling-local-settings

--------------------------------------

> I did not create termonad.hs config file in `~/.config/termonad/` dir

I don't think Termonad will create the `~/.config/termonad/termonad.hs` file, so maybe you had created this at some point in the past?

**Comment by Minda1975** [comment]
> I don't think Termonad will create the `~/.config/termonad/termonad.hs ` file, so maybe you had created this at some point in the past?

Hello.  Yes. I created this file. Then I tried to run it with a manually created configuration file.  Then I saw this error.  I deleted this file, but the problem remained the same. So, I deleted the whole termonad directory, located in `~/.cache`, and error messages is gone. However, I still wanted to configure termonad using `termonad.hs`.  After stepping deeper, I realized that I needed to install a separate package called `libghc-termonad-dev`, which apparently attracted other necessary dependencies. So, my problem is solved. You can close this issue.

> somewhat confusing

That's right ....

Maybe the README could be fixed so that people using Debian systems know what dependencies are needed.

**Comment by cdepillabout** [comment]
Thanks for the update.

If you're interested in helping out, could you send an update to the README with instructions on what to install on Debian?  The README currently doesn't have any instructions for installing using a distro package manager.

Also, maybe you could report your frustrations to the Debian packagers?

**Comment by clinty** [comment]
FYI, the Debian `termonad` package now expresses a weak dependency on `libghc-termonad-dev`, which should pre-empt this issue on most setups.

**Comment by cdepillabout** [comment]
@clinty Thanks for letting us know!
