### ISSUE TITLE
Update README adding instructions for installing Termonad through Debian's apt package manager

### ISSUE THREAD

**Issue by Minda1975** [cdepillabout/termonad#198]
Hello. I don’t know if I’m writing in the right place, but I would like the README to be improved with instruction for those who use package manager in the Debian system. 

For simply installation, you can install `termonad` with command `sudo apt install termonad`. This way you install a program that is fully usable, but the functionality of any configuration  is limited.  To fully configure this program, you should install the package called `libghc-termonad-dev`. This way you will be able to fully configure Termonad using  a Haskell-based settings file `termonad.hs`

P.S.

I have already [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993519) about this problem  to the  Debian Haskell Group.

P.S.S.

My report on this issue is currently closed, with this comment 

> We believe that the bug you reported is fixed in the latest version of
haskell-termonad, which is due to be installed in the Debian FTP archive. Thank you for reporting the bug, which will now be closed.

**Comment by cdepillabout** [comment]
@Minda1975 Thank you for creating this issue.

Please feel free to send a PR  explaining how to install Termonad through `apt`.

I imagine @clinty might be interested in doing this as well, since they appear to be the maintainer for Termonad in Debian.

**Comment by cdepillabout** [comment]
Solved in #201, thanks!
