### ISSUE TITLE
CI failure due to backwards-incompatible aeson change

### ISSUE THREAD

**Issue by gelisam** [cdepillabout/termonad#209]
I believe the CI failures in #206 are not due to changes in my PR, but rather, to a backwards-incompatible aeson change (presumably the much publicized [switch away from `HashMap`, due to the discovery of a collision attack](https://github.com/haskell/aeson/pull/866)).

I can reproduce this on `master` by running `cabal update` before `cabal build`, so this probably requires both publishing revisions with new upper bounds and updating HEAD to be compatible with aeson-2.x. And possibly some CPP magic to continue to be compatible with aeson-1.x.

**Comment by cdepillabout** [comment]
Thanks for bringing this up.

I published a revision for `termonad-4.2.0.0` (the current latest version), that makes sure to put an upper bound on `aeson`: https://hackage.haskell.org/package/termonad-4.2.0.0/revisions/
