### ISSUE TITLE
generate correct links in the haddocks on hackage to the gi-gtk documentation

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#5]
In the [Haddocks](https://hackage.haskell.org/package/termonad-0.2.1.0/docs/Termonad-Term.html) on Hackage for Termonad, links are not generated correctly for types that come from the `gi-*` libraries, notably [`gi-vte`](https://hackage.haskell.org/package/gi-vte) and [`gi-gtk`](https://hackage.haskell.org/package/gi-gtk).

For example, see how links are not generated for the [`relabelTab`](https://hackage.haskell.org/package/termonad-0.2.1.0/docs/Termonad-Term.html#v:relabelTab) function.

There are a couple things that need to be done to fix this:

- First, make sure Hackage can actually build the documentation for Termonad.  I've opened up an issue about this [here](https://github.com/haskell-CI/hackage-matrix-builder/issues/50#issuecomment-413772206).
- In the meantime, I'm using the script [scripts/hackage-docs.sh](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/scripts/hackage-docs.sh) to generate the Haddocks and then upload them to Hackage.  I don't know why generating the documentation like this doesn't create proper links to the `gi-*` libraries.  An issue should probably be posted about this on the [haskell-gi](https://github.com/haskell-gi/haskell-gi) repository.

**Comment by LSLeary** [comment]
I don't know why, but fwiw I do see links to `gi-*` libraries in the Termonad haddocks generated by nix.

**Comment by cdepillabout** [comment]
This looks like it is working now.  The termonad-1.0.0.0 release has correct documentation.

I *think* this was fixed by setting the documentation to be generated by default for the haskell-gi packages:

https://github.com/cdepillabout/termonad/blob/57157c716d6233fa24f8756b6a2ab182702f1ace/.nix-helpers/nixpkgs.nix#L62-L68

I'd like to get this setting to be the default in nixpkgs:

https://github.com/NixOS/cabal2nix/issues/386
