### ISSUE TITLE
fix computational complexity in the FocusList module

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#64]
A [`FocusList`](https://github.com/cdepillabout/termonad/blob/de2abaaf75b1948470b61a168d9c8397bbc459b0/src/Termonad/FocusList.hs#L53-L57) represents an ordered list with a given item having the [`Focus`](https://github.com/cdepillabout/termonad/blob/de2abaaf75b1948470b61a168d9c8397bbc459b0/src/Termonad/FocusList.hs#L54).  There should be efficient ways to insert an item, remove an item, and figure out the rank (the index) of a given item.  Termonad uses a `FocusList` to hold the terminal tabs.

Unfortunately, under the hood, `FocusList` is currently implemented with a `IntMap` to keep track of the index of each item in the `FocusList`:

https://github.com/cdepillabout/termonad/blob/de2abaaf75b1948470b61a168d9c8397bbc459b0/src/Termonad/FocusList.hs#L56

This makes inserting and removal slower than necessary, since the keys for the other items in the `FocusList` need to be adjusted.

It would be nice to change `FocusList` to use a different data structure that gave better computational complexity for insertion and removal.  Ideally, It would be `O(lg n)` for insertion, removal, and the rank operation.  (Or `O(1)` if possible.)

I'm not sure what would be the best data structure for this, but after a little googling it looks like there is a data structure called an [Order statistic tree](https://en.wikipedia.org/wiki/Order_statistic_tree) that promises this computational complexity.  Not sure if it also works as a purely functional data structure.

This issue could be something a beginner could tackle, because there are currently many tests to make sure the `FocusList` works correctly.  Also, all the changes should be limited to the `FocusList` module.  All you would need to do would be to make sure your changes passed the current test suite.  However, it would be a non-insignificant amount of work.

Eventually `FocusList` should be forked off to an external package.

**Comment by cdepillabout** [comment]
Also, all the methods exposed from the `FocusList` module should have the computational complexity added to the haddocks as a big-O value.

**Comment by Grendel-Grendel-Grendel** [comment]
http://hackage.haskell.org/package/order-statistic-tree-0.1.1.0/docs/Data-OSTree.html This library looks like it would work fine. It's all O(log(n)) and will be blazingly fast even if the user has a ridiculous amount of tabs. I would get to work on this but I can't seem to figure out how to add this package with the way stack is set up here. Could you lend me a hand? I can get right to work then.

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel Thanks for taking a look at this.

I think you should be able to add that library by adding it to the `extra-deps` section in the `stack.yaml` file.

However, it looks like `order-statistic-tree` has a dependency on `base ==4.8`, which means it will only work with older versions of base (and hence, older versions of GHC).  You would need to send a PR to `order-statistic-tree` to update it to work with new versions of base, so you can use it with GHC-8.4.3.

**Comment by Grendel-Grendel-Grendel** [comment]
I sent a PR. We will have to see how long it takes for them to respond, though.

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel Thanks!  Could you send a link to the PR?

**Comment by cdepillabout** [comment]
Thanks for the link.

We'll have to wait and see if this is merged in.  If not, we may have to fork it and either re-implement it in Termonad, or just upload our own OSTree package.

I don't think `FocusList` necessarily needs `Functor`, so I guess that is okay.

**Comment by Grendel-Grendel-Grendel** [comment]
It also needs instances of `Traversable` and `Foldable` unless we can factor those out as well.

**Comment by cdepillabout** [comment]
> The `OSTree` is not a map. Many of the functions in FL (and some of the invariants) are build around there being a map.

So the current `FocusList` implementation is using an `IntMap`.  However, this `IntMap` has a very specific form.  For instance, if there are 5 items in the `FocusList`, then keys in the `IntMap` are always 0, 1, 2, 3, 4.  If you remove one item from the `FocusList`, for instance the item at index 2, then the items at index 3 and 4 are shifted down so the keys become 0, 1, 2, 3.  The keys in the `IntMap` will always be `[0..n]`.

There is a lot of code in the `FocusList` module that protects this invariant.

I think that if we use the correct data structure (like `OSTree`), then we get this invariant for free.  I _think_ an `OSTree` gives us a way to get an item at index 2 in `O(lg n)`, and oppositely a way to figure out the index for a given item in `O(lg n)`.  I think this is the only "map-like" functionality that is needed for the `FocusList`.

Another way to think about this is to see which `FocusList` functions are being used in the rest of the code currently.  You could grep for functions ending in `FL` through the rest of the code.  This should give you a good idea of what is being used.

**Comment by Grendel-Grendel-Grendel** [comment]
Ok, I've been grepping the code already and made some progress. One more question I should have asked. It doesn't appear like there is a way to insert values at n-index into the tree. If this is necessary I could try and write a way to do it into the tree but if the ordinary `insert` function of the tree works fine then I'll just axe the indexed insert functions.

**Comment by cdepillabout** [comment]
> It doesn't appear like there is a way to insert values at n-index into the tree. If this is necessary I could try and write a way to do it into the tree but if the ordinary insert function of the tree works fine then I'll just axe the indexed insert functions.

Is this for the `OSTree`?

For `Termonad`, the list of terminals is held in the `FocusList`.  Sometimes a new teriminal is needed to be created in the middle of the existing list.  I think this requies inserting at a given n-index.  Are you saying that the `OSTree` doesn't support this operation?

If so, then maybe the `OSTree` can be changed to support this in `O(lg n)`?  Or maybe we need to find a new data type?

**Comment by Grendel-Grendel-Grendel** [comment]
On second thought I don't think `OSTree` works. It organizes elements based on their `Ord` class. The "index" of an element just says that it is the nth smallest value. If I understand this is not at all what we want.

If I understand correctly we require these operations to be fast.
-**selection**:
-**lookup**: of an element (maybe not necessary that it be super fast, `findFL` is used in one place)
-**insertion/deletion**: At the moment this is what seems most expensive since it requires shifting the index keys of the `IntMap`. `IntMap` otherwise is fast at insertion and deletion
-**updates:** this is already pretty fast but could be O(1) instead of O(min(n,W)) unless the overhead of O(1) was too much.
-**indexing**: Is it really faster to have the index of every element kept track of and updated manually then to calculate index on-the-spot? 

It seems to me that boxed `Vector` would be best for this. Appending and prepending would be slower, (and I believe we don't use prepending) but we could avoid true appending by having the Vector start out at some default size which would be larger than the number of tabs someone is likely to use, and keep track of the virtual length of the `FocusList` separately. I doubt for example, that someone is likely to have much more than 30 tabs open. We could then take advantage of the speedy O(1) updates. This would have some overhead though so maybe it is a bad idea. In this case as long as tabs stay below a certain number it would be O(1), and if someone went beyond the current "limit" it would become O(n) until it shrunk back down again.

 Inserting something into the middle would be slightly slower, though not _that_ slow. The Vector could be split at an index (O(1)) the element deleted/inserted and then the two concatenated (O(n+m)). Combined with the "oversized array" solution above this would also mean it would concatenate empty stuff. Past the standard size though, this would actually be equivalent to IntMap in terms of growth rate. Currently, we don't insert into the middle of the list either. 

Overhead aside (and I don't know about the overhead) It seems to me like a `Vector` based `FocusList` would be superior if we are reading and writing the elements more often than we are looking for their index. Otherwise, it should be better for all normal purposes. 

Am I overlooking anything?

**Comment by cdepillabout** [comment]
Thanks for summarizing what we need. You may be right about `OSTree`.  It may not be exactly what we want.  Let me respond to the rest of the points inline:

> - **selection**

Just for clarity, this means finding an item in the `FocusList` based on its index.

> - **lookup**: of an element (maybe not necessary that it be super fast, `findFL` is used in one place)

Based on the type of `findFL :: (Int -> a -> Bool) -> FocusList a -> Maybe (Int, a)`, this will necessarily have to traverse the entire list, and be `O(n)`.

It would be neat to have a function like `lookupFL :: Ord a => a -> FocusList a -> Maybe Int` that would lookup the index of an element in something like `O(lg n)`, but maybe we aren't using this functionality currently?  And maybe this wouldn't be possible unless we knew that all `a`s have an `Ord` instance when constructing the list.

For now, I think it is okay for `findFL` to be `O(n)`.

> - **insertion/deletion**: At the moment this is what seems most expensive since it requires shifting the index keys of the `IntMap`. `IntMap` otherwise is fast at insertion and deletion

This is correct.  I'd like some solution that doesn't require shifting the index keys, but instead keeps track of them using the data structure that stores them.  See the next point.

> - **indexing**: Is it really faster to have the index of every element kept track of and updated manually then to calculate index on-the-spot? 

I think this might be true.

What I was imagining was some sort of tree that keeps track of how many leaves are below each node.

Here's a picture to describe this:

![labelednodes](https://user-images.githubusercontent.com/64804/47763899-f7fe1900-dd05-11e8-951d-6f6a6ba3c5d5.png)

Other than the leaves (which only contain terminals), each node is labeled with how many leaves are below it.  I was thinking that having this type of information inherent in the tree would make it easy to figure out the index of a given terminal.

Inserting a new terminal would require only the affected nodes to be relabeled, which would hopefully be `O(lg n)`.


> It seems to me that boxed Vector would be best for this.

The problem with `Vector` is pretty much as you have described.  Inserting into the middle of the list would be `O(n)`, while I'm hoping we would figure out a tree-based solution that would be `O(lg n)`.

**Comment by Grendel-Grendel-Grendel** [comment]
You’re correct about how the OSTree functions, but I don’t see how this
will enable us to detect the index of the tree. Do you want to keep these
elements still as pairs with the index? We would still have to perform a
shift operation, but if I’m not mistaken this wouldn’t be faster, the
number of resources required still would increase linearly. If we insert an
element at index i, we still have to perform one shift for each element
from i to the end of the list. One thing that might remedy this somewhat
(though it may be overkill) would be that the tree would allow us to take
advantage of parallelization. Inserting an element into the middle of what
would be the sorted list would then require searching down the tree until
we found the branch that currently possesses its index, shifting it and
everything forward up by one, joining the element into the original tree,
and then joining the shifted branch back in. I could see how to do this.
This seems like it would be a datastructure unto itself, however.

**Comment by cdepillabout** [comment]
> You’re correct about how the OSTree functions, but I don’t see how this will enable us to detect the index of the tree.

With my previous comment, I was talking about some sort of theoretical tree data structure.  I'm not actually sure how the OSTree works under the hood!

I was hoping there would be some sort of theoretical data structure that works like I described above.  And I'm not actually sure how it would enable us to detect the index of a given element.  I was hoping that with my theoretical data structure, there would be an easy, well-known algorithm to figure out the index of a given element, based on the numbers in its parents' nodes.

> Do you want to keep these elements still as pairs with the index?

I was hoping that with my theoretical data structure like above, we wouldn't have to keep the elements as pairs with the index, but instead be able to figure out the index on-the-fly, based on the numbers in its parents' nodes (as you hinted at above).  I'm thinking this would be `O(lg n)`.

> We would still have to perform a shift operation,

When inserting and removing an element, I'm thinking some tree rotations would need to happen to keep the tree balanced, similar to what would happen for an AVL tree, red-black tree, splay tree, etc.  During these tree rotations, the parent nodes might have to be relabeled with the correct number of children under them.  I'm hoping these operations would only be `O(lg n)`.


If the OSTree doesn't give us this ability, then we might have to look for another data structure that gives us this!

**Comment by Grendel-Grendel-Grendel** [comment]
the balancing and rotating shouldn’t be a problem as the functions are
already ther in OSTree. I’m not sure if we can have fast inserting and
removing while at the same time having fast/implicit indexes. We *can*
figure out what the index of any element is given its node, but this tree
requires that our elements have an ‘Ord’ instance, and then we end up with
the same problems as we have now.

I have been asking about and some people have suggested looking into a
priority queue. I will get to that.

**Comment by cdepillabout** [comment]
Oh nice, I just read through the explanation of [`Data.Sequence`](http://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Sequence.html).  It looks like the properties are pretty good, and will hopefully be able to be used to give us the performance as described above!

**Comment by Grendel-Grendel-Grendel** [comment]
I already have rewritten the module. As soon as I am in a place with reliable internet I will make a PR. Some of the tests have failed though the ones that have failed I believe are because the tests need to be adjusted to the new data type or will be quickly fixed. I don’t know how the test suite works and couldn’t find the source of the failures searching the relevant directory so hopefully you or LSLeary can patch that up or tell me where to look.

Also, something I noticed is that the Focus if a FocusList is just an index. Couldn’t we get O(1) on getting the focus if we kept a copy of the element at that index alongside said index? This seems like it would have good benefits without significant drawbacks, unless you were using extremely large objects and having a duplicate of the focus was taxing on memory.

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel #76 has been merged in.  Thanks!

> Something I noticed is that the Focus if a FocusList is just an index. Couldn’t we get O(1) on getting the focus if we kept a copy of the element at that index alongside said index?

I think this would work.  However, now getting the element at the `Focus` has only logarithmic complexity, so it should be pretty fast, even for a big list.  The only time you'd need it to be `O(1)` is if you have a HUGE list, and you frequently need to manipulate the list and then get the new focus.  Of course, your list manipulation functions are mostly(?) `O(log n)`, so I'm thinking most of the benefit of keeping a copy of the element at the index would be lost!
