### ISSUE TITLE
add function that tests the invariants for TMState

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#8]
There are a few invariants for [TMState](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/src/Termonad/Types.hs#L108).  It would be great to add a function that tests these invariants.

It could be added as an assertion to the beginning of various Termonad functions.  Ideally the assertion would only be run if Termonad was compiled in some sort of debug mode.  (There could be a new cabal flag added to enable debug mode.)

Here are some invariants to test for:

- The actual notebook tabs in the GTK `Notebook` are in the same order as the tabs in the [`FocusList`](https://github.com/cdepillabout/termonad/blob/f161082f02af901c39f62c80eb9811546ff2daee/src/Termonad/Types.hs#L82-L84).  (The reverse should also be tested.)

- The terminal that has the focus in the `FocusList` is actually the correct one that really has the focus in GTK.  (The reverse should also be tested.)

**Comment by Grendel-Grendel-Grendel** [comment]
Hey, trying to take up a more difficult issue this time.

Where exactly is the GTK side of this? I have an idea about what to do to get the relevant tests, I just don't know where to find all the relevant elements.

**Comment by cdepillabout** [comment]
Okay, so the main idea is that you have a function that takes a [`TMState`](https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Types.hs#L108) and returns a `Bool` for whether or not it is internally sound.  (Well, actually it should be a `IO Bool`, since you'll need to call the GTK and VTE functions for doing the checking.)

There's actually an example of an invariant function for the focus list:

https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/FocusList.hs#L130

The invariant function for `TMState` will be somewhat similar.

@Grendel-Grendel-Grendel If you (or anyone else) is interested in working on this, it might be a good idea to start with checking that the terminal that has the focus in the [`FocusList`](https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Types.hs#L84) is actually the one that has the focus in the GTK [`Notebook`](https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Types.hs#L83).  In order to do this, you'll probably need to use functions from the [`FocusList` module](https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/FocusList.hs) to get the focused [`ScrolledWindow`](https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Types.hs#L54), and some function from [GI.Gtk.Objects.Notebook](http://hackage.haskell.org/package/gi-gtk-3.0.24/docs/GI-Gtk-Objects-Notebook.html) to get the GTK Object in the focused tab, and compare it to the `ScrolledWindow`.  I'm not sure how to compare GTK objects to make sure they are the same, but I would think there would be a way.  You might need to ask in the [haskell-gi gitter](https://github.com/haskell-gi/haskell-gi).

**Comment by Grendel-Grendel-Grendel** [comment]
If I'm not mistaken here and looking at the wrong libraries, gtk widgets have an [`Eq` instance.](http://hackage.haskell.org/package/gtk-0.15.0/docs/Graphics-UI-Gtk-Abstract-Widget.html). So does `ScrolledWindow`. So it looks to me like the function simply needs to grab the focus (which if I understand correctly is the first element in the focuslist) and grab the notebook object. Then they just need to be unpacked so that they're both widgets and can get compared.

The only obstacle left then is that the `createTerm` function is a little daunting. If you could point out to me where the variables that need to be fed (at the beginning and end) into our new invariant function  are within `createTerm` everything else should be clear I can get right to work. Thanks ahead of time.

**Comment by Grendel-Grendel-Grendel** [comment]
Ok, so I've been looking at the `tmState` type and have started writing the function. I imagine the focused tab in the notebook is the current page, and that's quick to find, but where exactly is the relevant `focusList` in `tmState`? Other than that it seems like there is an `Eq` instance for gtk widgets so if we strip these things down to widgets then they can be compared.

**Comment by cdepillabout** [comment]
> I imagine the focused tab in the notebook is the current page, and that's quick to find, but where exactly is the relevant focusList in tmState?

I think you're probably right about the focused tab in the notebook being the current page.

`TMState` is actually a data type wrapped in an `MVar`:

https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Types.hs#L158

Here is `TMState'`:

https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Types.hs#L108-L121

The `TMNotebook` type contains the GTK `Notebook` as well as the `FocusList`:

https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Types.hs#L82-L85

The GTK `Notebook` and this `FocusList` are what you should be operating on.

> Other than that it seems like there is an Eq instance for gtk widgets so if we strip these things down to widgets then they can be

Oh okay, I didn't realize this.  This might make things a little easier!

> Im also a little fused about what variables are holding the tmState at the beginning and end of createTerm as it is a rather daunting and hard to read function.

`createTerm` is definitely too long.  Definitely feel free to refactor it.

The `mvarTMState` arg contains the `TMState'` that you'll need to test: 

https://github.com/cdepillabout/termonad/blob/9b7a6ce6009c2a380df7c3b858b57d2609716247/src/Termonad/Term.hs#L274-L275

It would probably be easiest to pass `mvarTMState` directly into the invariant function.  So the invariant function would have a type signature like this:

```haskell
invariantTMState :: TMState -> IO Bool
```

You'll need to pull the `TMState'` out of the `MVar` to actually be able to work on it.  I think you should be able to do this with the `readMVar` function.

As an aside, I guess it might also be nice to have a function like the following:

```haskell
assertTMStateInvariant :: TMState -> IO ()
```

This could throw an error if the invariant was violated, as well as printing to the screen exactly which invariants are violated.  This might actually be the function you want to call in the beginning and end of `createTerm`.

**Comment by Grendel-Grendel-Grendel** [comment]
Ok, cool, that should be all the info I need. Thanks for the detailed response. Should be easy now, just unpacking some boxes and putting them in `==`. Also, I was planning on writing this function using the `assert` function from the beginning. Simply adding that into the function should do exactly what you want.

You should make an issue for refactoring CreateTerm. We can make it a little prettier and easier to understand by breaking it into more basic parts and having it run each part as a function belonging to it. The biggest problem I found with it was that it was not (and still isn't) clear what each part was doing. Adding comments for each section will also fix that. It seems to be the central function at work here and the easier it is to figure out the easier it will be for new contributors to figure out the rest of the program, the more people can develop.

Lastly, have you seen [this](https://github.com/NorfairKing/validity) library for invariant testing? We sure have a lot of custom types, but I'm unsure if this would streamline or bloat this process.

**Comment by Grendel-Grendel-Grendel** [comment]
Correct me if I'm wrong but doesn't the latter test encapsulate the former?

**Comment by Grendel-Grendel-Grendel** [comment]
So it seems to me like the easiest thing to do would be to make the `FocusList` into an ordinary list of widgets and to do the same thing to the notebook, and to compare these lists. A function could return a list of `Maybe TMStateInvariantErr`. This could get fed into our existing assert function.

A possible problem with this approach is that in the event of a failure then, it wouldn't be clear which tabs mismatching caused the errors. We could just say to hell with this and have a general `TabFLMismatch` error happen if this doesn't matter.

I await your thoughts.

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel yeah, I think your plan sounds good.

I imagine the first step would be adding an additional error like this:

```haskell
data TMStateInvariantErr
  = FocusNotSame FocusNotSameErr Int
  | TabsDoNotMatch TabsDoNotMatch
  deriving Show

data TabsDoNotMatch =
  TabLengthsDifferent Int Int -- ^ The first 'Int' is the number of tabs in the actual GTK 'Notebook'.  The second 'Int' is the number of tabs in the 'FocusList'.
  TabAtIndexDifferent Int -- ^ The tab at index 'Int' is different between the actual GTK 'Notebook' and the 'FocusList'.
```

Then in the actual code, you could compare the number of tabs in the focuslist vs the actual notebook, and return a `TabLengthsDifferent` error if they are different.

If they are the same, then you can go through the actual list and return `TabAtIndexDifferent` if one of the tabs is actually different.  You can probably just stop at the first difference you find.  I think folding over the `FocusList` might be the easiest way to implement this, but you also might be right that just changing both of them to a normal list and iterating over this might be easiest.

Also, feel free to change the name of the errors!

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel This issue has been fully implemented in master, right?  If so, I want to ahead and close this issue.

Thanks for working on this!

**Comment by cdepillabout** [comment]
From looking at the code, I believe this has been fully implemented in master.
